site_dir: site
docs_dir: docs
site_url: https://otplet.cassano.fe.it

plugins:
  - mike

theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan

extra:
  version:
    provider: mike

extra_css:
  - /assets/theme.css