name: CI

on:
  push:
    branches:
      - '**'          # all branches
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: make setup
      - run: make build
      - run: make test

      - name: Generate coverage
        run: |
          go test ./... -coverprofile=coverage.out
          mkdir -p coverage
          go tool cover -html=coverage.out -o coverage/index.html

      # optional: store for debugging
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/