name: Create GH Pages (MkDocs + mike)

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install mkdocs mkdocs-material mike

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # main → /dev/
      - name: Deploy dev docs
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          mike deploy --branch gh-pages --push dev dev

      # tag vX.Y.Z → /vX.Y.Z/ + aggiorna /latest/
      - name: Deploy release docs
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy --branch gh-pages --push --update-aliases "${{ github.ref_name }}" latest